-- Add investment ideas tracking to hub schema
-- Allows users to save, rate, and manage investment ideas across multiple categories

CREATE TABLE hub.investment_ideas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('stocks', 'real_estate', 'transportation', 'tech', 'other')),
  title TEXT NOT NULL,
  rationale TEXT,
  risk_level TEXT CHECK (risk_level IS NULL OR risk_level IN ('low', 'medium', 'high')),
  time_horizon TEXT CHECK (time_horizon IS NULL OR time_horizon IN ('short', 'medium', 'long')),
  capital_required TEXT,
  expected_returns TEXT,
  related_assets TEXT[],  -- tickers, REIT codes, company names as array
  action_items TEXT[],    -- research steps as array
  is_ai_generated BOOLEAN DEFAULT FALSE,
  source TEXT NOT NULL DEFAULT 'user' CHECK (source IN ('user', 'claude')),
  rating INTEGER CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'researching', 'pursuing', 'passed')),
  is_favorite BOOLEAN DEFAULT FALSE,
  user_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX idx_investment_ideas_user_id ON hub.investment_ideas(user_id);
CREATE INDEX idx_investment_ideas_category ON hub.investment_ideas(category);
CREATE INDEX idx_investment_ideas_status ON hub.investment_ideas(status);
CREATE INDEX idx_investment_ideas_is_favorite ON hub.investment_ideas(is_favorite);
CREATE INDEX idx_investment_ideas_ai_generated ON hub.investment_ideas(is_ai_generated);

-- Enable Row Level Security
ALTER TABLE hub.investment_ideas ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only see their own investment ideas
CREATE POLICY "Users can view their own investment ideas"
  ON hub.investment_ideas
  FOR SELECT
  USING (auth.uid() = user_id);

-- RLS Policy: Users can insert their own investment ideas
CREATE POLICY "Users can create their own investment ideas"
  ON hub.investment_ideas
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can update their own investment ideas
CREATE POLICY "Users can update their own investment ideas"
  ON hub.investment_ideas
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can delete their own investment ideas
CREATE POLICY "Users can delete their own investment ideas"
  ON hub.investment_ideas
  FOR DELETE
  USING (auth.uid() = user_id);

-- Add investment_categories to preferences table
ALTER TABLE hub.preferences
ADD COLUMN IF NOT EXISTS investment_categories TEXT[] DEFAULT '{"stocks","real_estate","transportation","tech","other"}'::text[];

-- Comment for clarity
COMMENT ON TABLE hub.investment_ideas IS 'User investment ideas with hybrid AI-generated and user-managed tracking';
COMMENT ON COLUMN hub.investment_ideas.is_ai_generated IS 'True if idea was generated by Claude, false if user-created';
COMMENT ON COLUMN hub.investment_ideas.related_assets IS 'Array of related tickers or asset codes (e.g., ["AAPL", "MSFT"] for stocks or ["VNQ"] for REITs)';
COMMENT ON COLUMN hub.investment_ideas.investment_categories IS 'User-enabled categories for investment ideas filtering';
